version: '3.8'

services:
  db:
    image: postgres:16
    container_name: otocom-postgres
    environment:
      POSTGRES_DB: otocom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: batuhan
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./
      dockerfile: Dockerfile

    container_name: otocom-backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: batuhan
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/otocom
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: batuhan
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    depends_on:
      - db

  frontend:
    build:
      context: ../otoApiUi
      dockerfile: Dockerfile
    container_name: otocom-frontend
    ports:
      - "4200:4200"
    restart: always
    depends_on:
      - backend


volumes:
  pgdata:

